### ISSUE TITLE
请标明出处

### ISSUE THREAD

**Issue by kajo-kurisu** [INDEX108/VINS_monodepth_constrain#1]
如果是作为开源项目使用，请标注出处；如果是作为论文使用，请记得引用我们的文章

**Comment by INDEX108** [comment]
您好，该代码仅作为开源项目。本项目没有使用D_VINS的源码，仅仅是在Ceres优化加入了基于Depth-Anything的单目深度约束，总架构图中的代码引用了D_VINS的开源工作，但是并没有在该代码中开源。

**Comment by INDEX108** [comment]
我会在图下标注回环检测部分引用的工作，感谢关注

**Comment by INDEX108** [comment]
顺便，方便问下您的工作发表到哪里了吗？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年6月19日(周三) 上午9:35
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [INDEX108/VINS_monodepth_constrain] 请标明出处 (Issue #1)




 
如果是作为开源项目使用，请标注出处；如果是作为论文使用，请记得引用我们的文章

**Comment by kajo-kurisu** [comment]
目前处在发表前的修改阶段，如果届时你需要发表论文，请记得对我们进行引用

**Comment by INDEX108** [comment]
好的，非常感谢您的开源工作。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年6月19日(周三) 上午10:13
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [INDEX108/VINS_monodepth_constrain] 请标明出处 (Issue #1)




 
目前处在发表前的修改阶段，如果届时你需要发表论文，请记得对我们进行引用
